global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:3001']  # utiliser le nom de service docker

  - job_name: 'game-service'
    static_configs:
      - targets: ['game-service:3002']  # idem ici
