name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build all Docker services
      run: |
        docker compose build

    - name: Test services (health check)
      run: |
        docker compose up -d
        sleep 10
        curl -f http://localhost:8080/auth || exit 1
        curl -f http://localhost:8080/game || exit 1
